//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASCO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        public int admin_id { get; set; }

        [Required(ErrorMessage = "Username cannot be empty")]
        [Display(Name = "Username")]
        public string admin_name { get; set; }

        [Required(ErrorMessage = "This field cannot be empty")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string admin_pass { get; set; }
    }
}
