//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer_Loan_RS
    {
        public int relationship_id { get; set; }
        public Nullable<int> farmer_id { get; set; }
        public Nullable<int> loan_id { get; set; }
        public Nullable<System.DateTime> loan_takendate { get; set; }
        public Nullable<System.DateTime> not_valid_until { get; set; }
    
        public virtual Farmer Farmer { get; set; }
        public virtual Loan Loan { get; set; }
    }
}
